repos:        
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
      - id: detect-private-key
      - id: check-added-large-files
      - id: check-symlinks
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
    
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        name: codespell
        description: Checks for common misspellings in text files.
        entry: codespell
        language: python
        types: [text]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.5.0
    hooks:
      # Run the linter.
      - id: ruff
        args: ["--fix", "--exclude", "tests"]
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.9"
    hooks:
      - id: bandit
        args: ["--exclude", "tests"]

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.3
    hooks:
    - id: python-safety-dependencies-check
      args: ["--ignore", "70612, 71167, 71064, 71199"]
      files: requirements.lock
